---
# Ignoring complaints about e.g. \b -> MkFileLogInitP a1 a2 b
- ignore:
    name: "Avoid lambda"

- ignore:
    name: Use <$>
    within:
      - "Shrun.Configuration.Args.Parsing.TH"

- ignore:
    name: "Avoid lambda using `infix`"
