---
resolver: nightly-2025-10-09
packages:
  - .
ghc-options:
  "$locals": -Wall
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-deriving-strategies
    -Wmissing-export-lists
    -Wmissing-exported-signatures
    -Wmissing-home-modules
    -Wpartial-fields
    -Wprepositive-qualified-module
    -Wredundant-constraints
    -Wunused-binds
    -Wunused-packages
    -Wunused-type-patterns
    -Wno-deprecations
    -Wno-unticked-promoted-constructors
extra-deps:
  - env-guard-0.2.1@sha256:f50499a07c5eddc8309b9896363e9861a28091f4f96254f9b76bc34426e25c79,1134
  - gitrev-typed-0.1@sha256:905b696dec9c52486290cfef2d3156420de83f5b21bfb0821a37822f40ee1568,3783
  - random-1.2.1.3@sha256:117541ba0a177397a3333f94870f789ef050dca31b0688a19824b2bc401b8823,6237
  - git: https://github.com/tbidne/algebra-simple.git
    commit: 37ec7127fbd0f591d4539e4bf72a0badd7569181
  - git: https://github.com/tbidne/bounds.git
    commit: b7ca541cfdd8564bcebe5d38456fe7abf77885b8
  - git: https://github.com/tbidne/exception-utils.git
    commit: 61a9e06a26adcca70d565105a1508a16022435a2
  - git: https://github.com/tbidne/fs-utils.git
    commit: 26136275027fd827574c5004ebd11b659d7abdab
  - git: https://github.com/tbidne/monad-effects.git
    commit: 7e2fa052e7215c9bf71c3149b5382abcc882b819
    subdirs:
      - lib/effects-async
      - lib/effects-env
      - lib/effects-fs
      - lib/effects-ioref
      - lib/effects-optparse
      - lib/effects-process
      - lib/effects-stm
      - lib/effects-time
      - lib/effects-terminal
      - lib/effects-thread
      - lib/effects-unix
  - git: https://github.com/tbidne/relative-time.git
    commit: be79249b8909dba64d3b301025d4d684f46ec2a1
  - git: https://github.com/tbidne/si-bytes.git
    commit: baf98b6945e32fc48b2e31e72ab3abaa966c4115
  - git: https://github.com/tbidne/smart-math.git
    commit: 4e10a4134f825ba825113955bb97be7f7e28ad6e
allow-newer: true
allow-newer-deps:
  - tasty
